name: General Issue
description: General issue tracker with structured questions
title: "General "
labels: []
assignees: []

body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Brief summary of the issue.
      placeholder: “A short and clear summary”
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve or what improvement does this provide?
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed Solution
      description: Describe your proposed approach.
    validations:
      required: false

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: Choose the category.
      options:
        - Feature Request
        - Documentation Issue
        - Performance Issue
        - Security Issue
        - Question/Support
        - Enhancement
        - Task
      default: 0
    validations:
      required: true

  - type: input
    id: priority
    attributes:
      label: Priority
      description: Choose from Critical, High, Medium, Low.
      placeholder: Medium
    validations:
      required: false

  - type: input
    id: additional
    attributes:
      label: Additional Context
      description: Any further details or references.
      placeholder: URLs, screenshots, etc.
    validations:
      required: false
